export const COURSE_ACTION = {
  GET_LIST: 'COURSE/GET_LIST',
  UPDATE_LIST: 'COURSE/UPDATE_LIST',
  UPDATE_STATE: 'COURSE/UPDATE_STATE',
  INCREASE_LESSON_LEARNED: 'COURSE/INCREASE_LESSON_LEARNED',
};
