export const GAME_ACTION = {
  GET_LIST: 'GAME/GET_LIST',
  UPDATE_LIST: 'GAME/UPDATE_LIST',
  UPDATE_FETCHING_STATUS: 'GAME/UPDATE_FETCHING_STATUS',
  UPDATE_GAME_INFO_USER: 'GAME/UPDATE_GAME_INFO_USER',
};
