export const GUESS_THE_WORD_ACTION = {
  GET_LIST: 'GUESS_THE_WORD/GET_LIST',
  UPDATE_LIST: 'GUESS_THE_WORD/UPDATE_LIST',
  UPDATE_STATUS: 'GUESS_THE_WORD/UPDATE_STATUS',
  UPDATE_MAX_LEVEL: 'GUESS_THE_WORD/UPDATE_MAX_LEVEL',
};
