export const LESSON_ACTION = {
  GET_LESSON_LIST: 'LESSON/GET_LESSON_LIST',
  UPDATE_STATUS: 'LESSON/UPDATE_STATUS',
  ADD_FAVORITE_LIST: 'LESSON/ADD_FAVORITE_LIST',
  UPDATE_LESSON_LIST: 'LESSON/UPDATE_LESSON_LIST',
  COMPLETE_LESSON: 'LESSON/COMPLETE_LESSON',
};
