export const LESSON_ACTION = {
  GET_LESSON_LIST: 'GET_LESSON_LIST',
  UPDATE_STATUS: 'UPDATE_STATUS',
  ADD_FAVORITE_LIST: 'ADD_FAVORITE_LIST',
  UPDATE_LESSON_LIST: 'UPDATE_LESSON_LIST',
  COMPLETE_LESSON: 'COMPLETE_LESSON',
};
