export const USER_ACTION = {
  REGISTER: 'USER/REGISTER',
  LOGIN: 'USER/LOGIN',
  LOGOUT: 'USER/LOGOUT',
  UPDATE: 'USER/UPDATE',
  UPDATE_LEARNT_LESSON: 'USER/UPDATE_LEARNT_LESSON',
  GET_INFO: 'USER/GET_INFO',
  INCREASE_MEDAL: 'USER/INCREASE_MEDAL',
  INCREASE_STREAK: 'USER/INCREASE_STREAK',
  CHANGE_AVATAR: 'CHANGE_AVATAR',
};
